### ISSUE TITLE
[BUG] Configuration reset after restarting the game

### ISSUE THREAD

**Issue by MC-luoluo** [QWERTZexe/AutoGG-Reimagined#1]
I modified a configuration in oneconfig. The configuration was correctly saved to the file and took effect. However, the configuration was reset when I restarted the game.
![图片](https://github.com/QWERTZexe/AutoGG-Reimagined/assets/113677351/40f355df-a044-4712-b5be-3001fd891a43)

After restart
![图片](https://github.com/QWERTZexe/AutoGG-Reimagined/assets/113677351/cdc636dd-f981-420c-be97-8cec575d80e6)

**Comment by QWERTZexe** [comment]
Hey @MC-luoluo , thanks for letting me know about this! I wasnt able to replicate this behaviour on any version of AutoGG-Reimagined. Hopefully, the next version (which releases VERY soon) fixes it. The new version also doesnt need the TRIGGER field and will be slated for removal in a later version. Thanks for your patience. I will ping you once the new version releases.

**Comment by MC-luoluo** [comment]
![图片](https://github.com/QWERTZexe/AutoGG-Reimagined/assets/113677351/940eb2e6-2a84-4e15-89ac-089c4cbf6e9d)

**Comment by MC-luoluo** [comment]
it also happens with quick join
In the quick join mod, restarting the game after modifying the configuration will also reset the configuration, and modifying the configuration again will not take effect.

**Comment by MC-luoluo** [comment]
I reported this issue to the developers of oneconfig and they said: "it might be because this mod developer isnt initializing their config correctly." and gave a kotlin example: [https://github.com/Polyfrost/Chatting/blob/ main/src/main/kotlin/org/polyfrost/chatting/config/ChattingConfig.kt#L22-L340](https://github.com/Polyfrost/Chatting/blob/main/src/main/kotlin/org/polyfrost/chatting/config/ChattingConfig.kt#L22-L340)

**Comment by MC-luoluo** [comment]
I thought this might help you troubleshoot the issue

**Comment by MC-luoluo** [comment]
Hello, I just want to remind you in case you forget, two months ago you said that this mod will be updated soon

**Comment by QWERTZexe** [comment]
I wasnt able to reproduce this, but if you made a pr fixing your issue id gladly accept it! (also sorry for the late reply)

**Comment by MC-luoluo** [comment]
I think this bug is similar to https://github.com/QWERTZexe/Quickjoin/pull/3, but I don't know if it is the case

**Comment by FlyModeZ** [comment]
i got the same issue

**Comment by QWERTZexe** [comment]
The next release will be released very soon. We already fixed this issue, didnt push to GitHub yet. Stay tuned!

**Comment by MC-luoluo** [comment]
I think it's been a long time, when will the new version be released

**Comment by QWERTZexe** [comment]
In exactly 20 hours, i set a timer :D

**Comment by QWERTZexe** [comment]
I'll publish it right now @MC-luoluo

**Comment by QWERTZexe** [comment]
@MC-luoluo Published! You can find it on modrinth or github!
